import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import WaterEffectBackground from "@/components/WaterEffectBackground";
import Sound from "@/components/Sound";

const inter = Inter({ subsets: ["latin"],
  variable : "--font-inter",
 });

export const metadata = {
  title: "Deepika Badiganti",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={clsx(inter.variable,"bg-background text-foreground")}>
        {children}
        <WaterEffectBackground />
        <Sound/>
        <div id="my-modal" />
      </body>
    </html>
  );
}
